[workspace]
resolver = "2"
members = ["fuel-telemetry", "fuel-telemetry-macros"]

[workspace.package]
version = "0.1.1"
edition = "2021"
authors = ["Fuel Labs <contact@fuel.sh>"]
homepage = "https://fuel.network/"
license = "Apache-2.0"
repository = "https://github.com/FuelLabs/fuel-telemetry"
